import type {AnsiColorPalette} from '@codeimage/store/editor/model';

export interface AnsiTheme {
  id: string;
  name: string;
  label: string;
  palette: AnsiColorPalette;
}

export const ANSI_THEMES: Record<string, AnsiTheme> = {
  default: {
    id: 'default',
    name: 'Default',
    label: 'Default (Dark)',
    palette: {
      black: '#1e1e1e',
      red: '#f14c4c',
      green: '#4ec9b0',
      yellow: '#dcdcaa',
      blue: '#569cd6',
      magenta: '#c586c0',
      cyan: '#9cdcfe',
      white: '#d4d4d4',
      brightBlack: '#808080',
      brightRed: '#f14c4c',
      brightGreen: '#4ec9b0',
      brightYellow: '#dcdcaa',
      brightBlue: '#569cd6',
      brightMagenta: '#c586c0',
      brightCyan: '#9cdcfe',
      brightWhite: '#ffffff',
      foreground: '#cccccc',
      background: '#1e1e1e',
      cursor: '#ffffff',
      cursorText: '#1e1e1e',
      selection: '#264f78',
      selectionText: '#ffffff',
    },
  },
  dracula: {
    id: 'dracula',
    name: 'Dracula',
    label: 'Dracula',
    palette: {
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
      foreground: '#f8f8f2',
      background: '#282a36',
      cursor: '#f8f8f2',
      cursorText: '#282a36',
      selection: '#44475a',
      selectionText: '#f8f8f2',
    },
  },
  solarizedDark: {
    id: 'solarizedDark',
    name: 'Solarized Dark',
    label: 'Solarized Dark',
    palette: {
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
      foreground: '#839496',
      background: '#002b36',
      cursor: '#839496',
      cursorText: '#002b36',
      selection: '#073642',
      selectionText: '#839496',
    },
  },
  solarizedLight: {
    id: 'solarizedLight',
    name: 'Solarized Light',
    label: 'Solarized Light',
    palette: {
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
      foreground: '#657b83',
      background: '#fdf6e3',
      cursor: '#657b83',
      cursorText: '#fdf6e3',
      selection: '#eee8d5',
      selectionText: '#657b83',
    },
  },
  nord: {
    id: 'nord',
    name: 'Nord',
    label: 'Nord',
    palette: {
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
      foreground: '#d8dee9',
      background: '#2e3440',
      cursor: '#d8dee9',
      cursorText: '#2e3440',
      selection: '#434c5e',
      selectionText: '#d8dee9',
    },
  },
  monokai: {
    id: 'monokai',
    name: 'Monokai',
    label: 'Monokai',
    palette: {
      black: '#272822',
      red: '#f92672',
      green: '#a6e22e',
      yellow: '#f4bf75',
      blue: '#66d9ef',
      magenta: '#ae81ff',
      cyan: '#a1efe4',
      white: '#f8f8f2',
      brightBlack: '#75715e',
      brightRed: '#f92672',
      brightGreen: '#a6e22e',
      brightYellow: '#f4bf75',
      brightBlue: '#66d9ef',
      brightMagenta: '#ae81ff',
      brightCyan: '#a1efe4',
      brightWhite: '#f9f8f5',
      foreground: '#f8f8f2',
      background: '#272822',
      cursor: '#f8f8f2',
      cursorText: '#272822',
      selection: '#49483e',
      selectionText: '#f8f8f2',
    },
  },
  oneDark: {
    id: 'oneDark',
    name: 'One Dark',
    label: 'One Dark',
    palette: {
      black: '#282c34',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#abb2bf',
      brightBlack: '#5c6370',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#ffffff',
      foreground: '#abb2bf',
      background: '#282c34',
      cursor: '#528bff',
      cursorText: '#282c34',
      selection: '#3e4451',
      selectionText: '#abb2bf',
    },
  },
  gruvboxDark: {
    id: 'gruvboxDark',
    name: 'Gruvbox Dark',
    label: 'Gruvbox Dark',
    palette: {
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
      foreground: '#ebdbb2',
      background: '#282828',
      cursor: '#ebdbb2',
      cursorText: '#282828',
      selection: '#3c3836',
      selectionText: '#ebdbb2',
    },
  },
  gruvboxLight: {
    id: 'gruvboxLight',
    name: 'Gruvbox Light',
    label: 'Gruvbox Light',
    palette: {
      black: '#fbf1c7',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#7c6f64',
      brightBlack: '#928374',
      brightRed: '#9d0006',
      brightGreen: '#79740e',
      brightYellow: '#b57614',
      brightBlue: '#076678',
      brightMagenta: '#8f3f71',
      brightCyan: '#427b58',
      brightWhite: '#3c3836',
      foreground: '#3c3836',
      background: '#fbf1c7',
      cursor: '#3c3836',
      cursorText: '#fbf1c7',
      selection: '#d5c4a1',
      selectionText: '#3c3836',
    },
  },
  tokyoNight: {
    id: 'tokyoNight',
    name: 'Tokyo Night',
    label: 'Tokyo Night',
    palette: {
      black: '#1a1b26',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
      foreground: '#c0caf5',
      background: '#1a1b26',
      cursor: '#c0caf5',
      cursorText: '#1a1b26',
      selection: '#33467c',
      selectionText: '#c0caf5',
    },
  },
  catppuccin: {
    id: 'catppuccin',
    name: 'Catppuccin',
    label: 'Catppuccin Mocha',
    palette: {
      black: '#11111b',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#cba6f7',
      cyan: '#94e2d5',
      white: '#cdd6f4',
      brightBlack: '#45475a',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#cba6f7',
      brightCyan: '#94e2d5',
      brightWhite: '#b4befe',
      foreground: '#cdd6f4',
      background: '#1e1e2e',
      cursor: '#f5e0dc',
      cursorText: '#1e1e2e',
      selection: '#45475a',
      selectionText: '#cdd6f4',
    },
  },
  materialOcean: {
    id: 'materialOcean',
    name: 'Material Ocean',
    label: 'Material Ocean',
    palette: {
      black: '#0f111a',
      red: '#ff5370',
      green: '#c3e88d',
      yellow: '#ffcb6b',
      blue: '#82aaff',
      magenta: '#c792ea',
      cyan: '#89ddff',
      white: '#a6accd',
      brightBlack: '#464b5d',
      brightRed: '#ff5370',
      brightGreen: '#c3e88d',
      brightYellow: '#ffcb6b',
      brightBlue: '#82aaff',
      brightMagenta: '#c792ea',
      brightCyan: '#89ddff',
      brightWhite: '#ffffff',
      foreground: '#eeffff',
      background: '#0f111a',
      cursor: '#ffcc00',
      cursorText: '#0f111a',
      selection: '#1f2233',
      selectionText: '#eeffff',
    },
  },
};

export const ANSI_THEME_KEYS = Object.keys(ANSI_THEMES) as (keyof typeof ANSI_THEMES)[];

export function getAnsiTheme(themeId: string): AnsiTheme {
  return ANSI_THEMES[themeId] ?? ANSI_THEMES['default'];
}

export function getAnsiColor(palette: AnsiColorPalette, colorIndex: number): string {
  if (colorIndex >= 0 && colorIndex <= 7) {
    const colors = [
      palette.black,
      palette.red,
      palette.green,
      palette.yellow,
      palette.blue,
      palette.magenta,
      palette.cyan,
      palette.white,
    ];
    return colors[colorIndex];
  } else if (colorIndex >= 8 && colorIndex <= 15) {
    const brightColors = [
      palette.brightBlack,
      palette.brightRed,
      palette.brightGreen,
      palette.brightYellow,
      palette.brightBlue,
      palette.brightMagenta,
      palette.brightCyan,
      palette.brightWhite,
    ];
    return brightColors[colorIndex - 8];
  } else if (colorIndex >= 16 && colorIndex <= 231) {
    const index = colorIndex - 16;
    const r = Math.floor(index / 36);
    const g = Math.floor((index % 36) / 6);
    const b = index % 6;
    const toColor = (v: number) => (v === 0 ? 0 : v * 40 + 55);
    return `rgb(${toColor(r)},${toColor(g)},${toColor(b)})`;
  } else if (colorIndex >= 232 && colorIndex <= 255) {
    const gray = (colorIndex - 232) * 10 + 8;
    return `rgb(${gray},${gray},${gray})`;
  }
  return palette.foreground;
}
